import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { recommendationsApi } from "../services/endpoints";
import type { Recommendation } from "../types";
import { Card, PageLoading, ErrorState, EmptyState, PriorityBadge, Badge } from "../components/ui";
import { getErrorMessage } from "../services/api";

const CATEGORY_ICON: Record<string, string> = {
  savings: "💰",
  investment: "📈",
  insurance: "🛡️",
  credit: "🏦",
  goal: "🎯",
};

const CATEGORIES = ["all", "savings", "investment", "insurance", "credit", "goal"];

export default function Recommendations() {
  const [recs, setRecs] = useState<Recommendation[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    recommendationsApi.list().then(setRecs).catch((err) => setError(getErrorMessage(err))).finally(() => setLoading(false));
  }, []);

  if (loading) return <PageLoading />;
  if (error) return <ErrorState message={error} />;

  const filtered = filter === "all" ? recs : recs.filter((r) => r.category === filter);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-ink-900">AI Recommendations</h1>
        <p className="text-sm text-ink-500 mt-1">
          Generated by a hybrid rule-based engine using your financial data, behavioral profile, risk tolerance, and goals.
        </p>
      </div>

      <div className="flex flex-wrap gap-2">
        {CATEGORIES.map((c) => (
          <button
            key={c}
            onClick={() => setFilter(c)}
            className={`text-xs px-3 py-1.5 rounded-full font-medium capitalize ${filter === c ? "bg-brand-600 text-white" : "bg-white border border-ink-200 text-ink-700 hover:bg-ink-50"}`}
          >
            {c}
          </button>
        ))}
      </div>

      {filtered.length === 0 ? (
        <Card><EmptyState title="No recommendations in this category" /></Card>
      ) : (
        <div className="grid gap-3">
          {filtered.map((r) => (
            <Link key={r.id} to={`/recommendations/${r.id}`}>
              <Card className="hover:border-brand-300 transition-colors">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex gap-3">
                    <span className="text-xl">{CATEGORY_ICON[r.category] || "💡"}</span>
                    <div>
                      <div className="flex items-center gap-2">
                        <p className="font-semibold text-ink-900">{r.title}</p>
                        {!r.is_read && <span className="w-1.5 h-1.5 rounded-full bg-brand-500" />}
                      </div>
                      <p className="text-sm text-ink-500 mt-1">{r.recommendation}</p>
                      <div className="mt-2"><Badge>{r.category}</Badge></div>
                    </div>
                  </div>
                  <PriorityBadge priority={r.priority} />
                </div>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
